[package]
name = "into_dynamo"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-dynamodb = "0.28.0"
thiserror = "1.0.39"

[workspace]
members = [
    "derive_into_dynamo",
]
